### PR TITLE
Bower fix, bower directory is dragula.js instead of dragula

### PR DESCRIPTION
**Pull request by pjcarly**

### CODE REVIEW

**Comment by jnslxndr** [comment]
hi.
this build failed, because the dependency of dragula in bower.json is not the latest.
doing the same too ;-)

**Comment by pjcarly** [comment]
I see, I'll send a new PR.

**Comment by jnslxndr** [comment]
:+1: 
@kalcifer is there a reason, why the addon uses `ember-cli@0.2.7`?
maybe we can combine this?

**Comment by pksjce** [comment]
Hi, no, I missed housekeeping. Did not update the version. Will do so later today.

**Pull request merged**
